### PR TITLE
Added run profiles for moco and web

### PR DESCRIPTION
**Pull request by wouterla**
mvn exec:java -Pmoco 
and: 
mvn exec:java -Pweb

Not running them in the background yet, since I can't figure out how to do that...

### CODE REVIEW

**Comment by wouterla** [comment]
Ah... Sorry. I suppose I should create separate branches for each change. Adding on to the same branch seems to append to the pull request.
I've been working on master too long:-)

The changes are all minor, though. Added the capability to run junit tests from ant, and run them by default. And an override for the webdriver to use, so I can use chrome.

**Comment by gdinwiddie** [comment]
If I merge this pull request, does it retain the 3 individual commits?

**Comment by gdinwiddie** [comment]
P.S. I got travis-ci working. It pulls in the jar files automatically, now.

**Comment by wouterla** [comment]
I think all the individual commits are kept.

**Pull request merged**
